#!/bin/bash
#PBS -l walltime=72:00:00
#PBS -l select=1:ncpus=60:mem=300gb
#PBS -N zinterproscan

NSLOTS=60
INPUT=/rds/general/user/hchown/home/global/data/shared-rep-pangenome.fa
OUTDIR=/rds/general/user/hchown/home/global/data/interproscan/gene_families

module load  java/oracle-jdk-11.0.10

cd /rds/general/user/hchown/projects/fisher-local-software/live/interproscan-5.67-99.0
./interproscan.sh -cpu $NSLOTS -d $OUTDIR -f TSV -goterms -T $TMPDIR -i $INPUT